import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';

const SITE = 'https://tokencalculator.dev';
const pagesDir = fileURLToPath(new URL('./src/pages/', import.meta.url));
const gitDateCache = new Map();

/** Last commit date for a source file, as an ISO string. Undefined when unknown. */
function lastCommitDate(file) {
  if (gitDateCache.has(file)) return gitDateCache.get(file);
  let iso;
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cI', '--', file], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    if (out) iso = new Date(out).toISOString();
  } catch {
    iso = undefined;
  }
  gitDateCache.set(file, iso);
  return iso;
}

/** Map a built URL back to the source file that produces it. */
function sourceFor(pathname) {
  const clean = pathname.replace(/^\/|\/$/g, '');
  const candidates = clean
    ? [`${clean}.astro`, `${clean}/index.astro`]
    : ['index.astro'];

  // Dynamic routes resolve to their template.
  if (/-token-counter$/.test(clean)) candidates.push('[provider]-token-counter.astro');
  else if (/^(es|ja|de|pt-BR)$/.test(clean)) candidates.push('[lang]/index.astro');
  else if (clean && !clean.includes('/')) candidates.push('[comparison].astro');

  for (const candidate of candidates) {
    const full = pagesDir + candidate;
    if (existsSync(full)) return full;
  }
  return undefined;
}

/**
 * Emit a _redirects file with explicit 301s for the no-trailing-slash form of every
 * page. Cloudflare's `html_handling: auto-trailing-slash` answers those with a 307,
 * which Google treats as a weak canonical signal and may keep re-crawling. A 301 is
 * the permanent signal we actually want.
 *
 * Generated from the real route list so it cannot drift as pages are added.
 */
function trailingSlashRedirects() {
  return {
    name: 'trailing-slash-301',
    hooks: {
      'astro:build:done': async ({ pages, dir, logger }) => {
        const rules = pages
          .map((page) => `/${page.pathname}`.replace(/\/+$/, ''))
          // The site root has no no-slash form, and a rule for it would loop.
          // Error pages are noindex and are served directly by the asset handler.
          .filter((path) => path.length > 1 && !/^\/(404|500)$/.test(path))
          .sort()
          .map((path) => `${path} ${path}/ 301`);
        if (!rules.length) return;
        const header = '# Generated by astro.config.mjs. Permanent redirects for the\n'
          + '# no-trailing-slash form of each page, so canonical signals consolidate.\n';
        const { writeFile } = await import('node:fs/promises');
        await writeFile(new URL('_redirects', dir), `${header}${rules.join('\n')}\n`, 'utf8');
        logger.info(`_redirects written with ${rules.length} permanent redirects`);
      },
    },
  };
}

export default defineConfig({
  site: SITE,
  output: 'static',
  i18n: {
    locales: ['en', 'es', 'ja', 'de', 'pt-BR'],
    defaultLocale: 'en',
    routing: { prefixDefaultLocale: false },
  },
  integrations: [
    sitemap({
      // Machine-readable API contract, so agents can discover it from the sitemap.
      customPages: [`${SITE}/openapi.json`],
      serialize(item) {
        const source = sourceFor(new URL(item.url).pathname);
        const lastmod = source ? lastCommitDate(source) : undefined;
        if (lastmod) item.lastmod = lastmod;
        return item;
      },
    }),
    trailingSlashRedirects(),
  ],
  vite: {
    plugins: [tailwindcss()],
    build: {
      // Ship modern syntax. The default target transpiles down far enough to add
      // helper code no current browser needs, which Lighthouse reports as legacy
      // JavaScript. These four cover every browser the analytics actually sees.
      // Browser targets only; naming an ES version alongside them is rejected.
      target: ['chrome111', 'edge111', 'safari16.4', 'firefox121'],
      cssTarget: ['chrome111', 'edge111', 'safari16.4', 'firefox121'],
    },
    esbuild: { legalComments: 'none' },
  },
});
